## Numpy

In [2]:
import numpy as np

In [13]:
a = np.array([4,5,6,2,3,8,9,0])
a

array([4, 5, 6, 2, 3, 8, 9, 0])

In [14]:
type(a)

numpy.ndarray

In [15]:
a.shape

(8,)

shape gives dimesion and size

In [10]:
b= np.array([[4,5,7,8,8],
             [3,9,3,2,7]])
b.shape

(2, 5)

In [16]:
c = np.array([[[4,5,7,8,8],
             [3,9,3,2,7]]])
c.shape

(1, 2, 5)

In [18]:
np.arange(2, 22, 2.5)   #you can pass float value in arange, while you can't pass it in simple range

array([ 2. ,  4.5,  7. ,  9.5, 12. , 14.5, 17. , 19.5])

In [25]:
# linspace

np.linspace(2,30,10)  #gives lineraly spaced 10 numbers between 2 and 30

array([ 2.        ,  5.11111111,  8.22222222, 11.33333333, 14.44444444,
       17.55555556, 20.66666667, 23.77777778, 26.88888889, 30.        ])

In [39]:
np.linspace(2,30,10,retstep=True)  #retstep gives step size

(array([ 2.        ,  5.11111111,  8.22222222, 11.33333333, 14.44444444,
        17.55555556, 20.66666667, 23.77777778, 26.88888889, 30.        ]),
 3.111111111111111)

In [177]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [178]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [8]:
np.full((3,3),dtype=int)

TypeError: full() missing 1 required positional argument: 'fill_value'

[Link for eye vs identity](https://stackoverflow.com/questions/28363447/what-are-the-advantages-of-using-numpy-identity-over-numpy-eye)

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [184]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [183]:
np.diag([2,4,5,8])

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 8]])

In [42]:
np.random.rand(5,3)

array([[0.07073578, 0.10197952, 0.45364258],
       [0.03788537, 0.2143803 , 0.45138782],
       [0.22089727, 0.67008498, 0.29087034],
       [0.83036944, 0.84725979, 0.14726633],
       [0.0842348 , 0.30477297, 0.15156695]])

In [45]:
np.random.randn(5,4)

array([[-0.1181336 , -1.06781416, -1.13719867,  0.63043813],
       [ 1.35518569, -1.04543479, -0.94979935, -0.11176669],
       [-0.84967826, -1.4955849 ,  0.47993995,  0.57473318],
       [ 0.39829423, -0.72821955,  0.93285365,  0.87821697],
       [ 0.32456316,  0.63629445, -0.30493127, -0.17945937]])

In [9]:
r1=np.random.randint(1,50,(5,4))
r1

array([[34, 35,  6, 36],
       [ 7, 45, 42, 30],
       [24, 21, 36, 11],
       [18, 13,  9, 32],
       [19, 33, 27, 43]])

#### Slicing 2d array

In [121]:
r1[1:3,1:]      #slicing in double dimension array , first is for rows and second is for columns

array([[19, 43, 48],
       [34,  5, 49]])

Masking

In [120]:
r1>20

array([[ True,  True, False, False],
       [False, False,  True,  True],
       [False,  True, False,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True]])

In [123]:
r1[r1>20]

array([47, 32, 43, 48, 34, 49, 34, 36, 41, 39, 40, 22])

Reshaping

In [130]:
r1.shape

(5, 4)

In [131]:
r1

array([[47, 32, 19, 16],
       [14, 19, 43, 48],
       [15, 34,  5, 49],
       [34, 20, 36, 41],
       [39,  2, 40, 22]])

In [129]:
#product of rows and column should be equal
r1.reshape(4,5)

array([[47, 32, 19, 16, 14],
       [19, 43, 48, 15, 34],
       [ 5, 49, 34, 20, 36],
       [41, 39,  2, 40, 22]])

In [10]:
r1.reshape(10,2)

array([[34, 35],
       [ 6, 36],
       [ 7, 45],
       [42, 30],
       [24, 21],
       [36, 11],
       [18, 13],
       [ 9, 32],
       [19, 33],
       [27, 43]])

Array Math

In [135]:
x1= np.array([[3,4,7,2],[3,5,2,1]])
x2= np.array([[6,3,5,6],[7,3,2,2]])

In [136]:
x1+x2

array([[ 9,  7, 12,  8],
       [10,  8,  4,  3]])

In [137]:
x1*x2          #elemental multipication

array([[18, 12, 35, 12],
       [21, 15,  4,  2]])

In [139]:
x2=x2.T         #transposing for matrix multipication
x2

array([[6, 7],
       [3, 3],
       [5, 2],
       [6, 2]])

In [140]:
x1@x2

array([[77, 51],
       [49, 42]])

BroadCasting

In [141]:
x=np.zeros((5,4))

In [142]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [144]:
x+100   #broadcasting

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [147]:
f=np.zeros((5,5))
f

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [152]:
a_row=np.array([10,38,28,20,34])

f+a_row

array([[10., 38., 28., 20., 34.],
       [10., 38., 28., 20., 34.],
       [10., 38., 28., 20., 34.],
       [10., 38., 28., 20., 34.],
       [10., 38., 28., 20., 34.]])

In [16]:
z=np.zeros((5,5))
a_col=np.array([34,2,3,78,3])
a_col=a_col.T
a_col

array([34,  2,  3, 78,  3])

In [162]:
z+a_col

array([[34.,  2.,  3., 78.,  3.],
       [34.,  2.,  3., 78.,  3.],
       [34.,  2.,  3., 78.,  3.],
       [34.,  2.,  3., 78.,  3.],
       [34.,  2.,  3., 78.,  3.]])

In [18]:
l1=np.random.randint(1,50,(5,4))
l1

array([[12,  9, 23, 32],
       [ 5, 17, 29, 10],
       [45,  8, 27, 23],
       [39, 30, 10, 15],
       [47, 40, 17, 30]])

In [19]:
np.argmin(l1)  #gives index of minimum element

4

In [20]:
np.argmax(l1) #gives index of maximum element

16

Statistical Functions

In [23]:
x= np.array([2,3,4,6,8])
x

array([2, 3, 4, 6, 8])

In [24]:
np.mean(x)

4.6

In [25]:
np.median(x)

4.0

np.var(x) in NumPy<br>
The `np.var(x)` function in NumPy calculates the variance of the array `x`. The variance is a measure of how spread out the values in the array are. It is calculated as the average of the squared deviations from the mean.


In [26]:
np.var(x)

4.64

np.std(x) in NumPy<br>
The `np.std(x)` function in NumPy calculates the standard deviation of the array `x`. The standard deviation is a measure of how spread out the values in the array are. It is calculated as the square root of the variance.


In [174]:
np.std(x)

2.1540659228538015

In [29]:
marks = np.array([30,31,32,40,90,95,97,98,99,100])

In [39]:
np.percentile(marks, 50)

92.5

In [185]:
np.square(a)

array([16, 36, 64, 25,  4])

In [188]:
np.power(a,4)

array([ 256, 1296, 4096,  625,   16], dtype=int32)

Flattening

In [190]:
np.ravel(l1)

array([10, 18, 31, 29, 27, 18, 28, 32, 48, 22, 41, 22,  1, 19, 14, 39, 29,
       25, 42, 46])

Stacking

In [194]:
np.vstack(a)

array([[4],
       [6],
       [8],
       [5],
       [2]])

In [195]:
v1 = np.array([1,2,3,4,5])
v2= np.array([5,6,7,8,9])

np.vstack([v1,v2,v1,v2,v2])

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])